Repository asfadmin/grfn-ingest, pull requests merged in 2023-04, with the labels that each got.

#196 Release v1.0.1
  .github/workflows/changelog.yml
  .github/workflows/labeled-pr.yml
  .github/workflows/release-checklist-comment.yml
  .github/workflows/release.yml
  .github/workflows/static_analysis.yml
  .github/workflows/tag-version.yml
  .github/workflows/test.yml
  CHANGELOG.md
  Makefile
  echo10-construction/src/main.py
  environment.yml
  tests/conftest.py
  tests/data/config.json
  tests/data/granule-amplitude.echo10
  tests/data/granule-coherence.echo10
  tests/data/granule-connectedComponents.echo10
  tests/data/granule-unwrappedPhase.echo10
  tests/data/granule.echo10
  tests/data/granule_data.json
  tests/data/inputs.json
  tests/data/sds_metadata.json
  tests/test_echo10_construction.py
Labels: patch

#199 Add tests for schema validation
  .github/workflows/static_analysis.yml
  Makefile
  cmr-token/cloudformation.yaml
  cmr-token/src/cmr_token.py
  echo10-construction/cloudformation.yaml
  echo10-construction/src/echo10_construction.py
  environment.yml
  ingest/cloudformation.yaml
  ingest/src/ingest.py
  invoke/cloudformation.yaml
  invoke/src/invoke.py
  notify/cloudformation.yaml
  notify/src/notify.py
  tests/conftest.py
  tests/data/sds_metadata_v3.json
  tests/test_echo10_construction.py
  tests/test_verify.py
  verify/cloudformation.yaml
  verify/src/verify.py
Labels: bumpless

#200 modify echo10-construction/src/main.py to include three additional at…
  echo10-construction/src/echo10_construction.py
  tests/conftest.py
  tests/data/sds_metadata_v3.json
  tests/data/v2/config.json
  tests/data/v2/granule-amplitude.echo10
  tests/data/v2/granule-coherence.echo10
  tests/data/v2/granule-connectedComponents.echo10
  tests/data/v2/granule-unwrappedPhase.echo10
  tests/data/v2/granule.echo10
  tests/data/v2/granule_data.json
  tests/data/v2/inputs.json
  tests/data/v2/sds_metadata.json
  tests/data/v3/config.json
  tests/data/v3/granule-amplitude.echo10
  tests/data/v3/granule-coherence.echo10
  tests/data/v3/granule-connectedComponents.echo10
  tests/data/v3/granule-unwrappedPhase.echo10
  tests/data/v3/granule.echo10
  tests/data/v3/granule_data.json
  tests/data/v3/inputs.json
  tests/data/v3/sds_metadata.json
  tests/test_echo10_construction.py
  tests/test_verify.py
Labels: bumpless

#204 fix typo in release-checklist-comment.yml
  .github/workflows/release-checklist-comment.yml
Labels: bumpless

#205 add CODEOWNERS
  .github/CODEOWNERS
Labels: bumpless

#209 fix typo in file name
  requirements-all.txt
  requirements-echo10-construction.txt
Labels: bug, bumpless

#210 Release v1.1.0
  .github/CODEOWNERS
  .github/dependabot.yml
  .github/workflows/deploy.yml
  .github/workflows/release-checklist-comment.yml
  .github/workflows/static_analysis.yml
  .gitignore
  CHANGELOG.md
  Makefile
  cmr-token/cloudformation.yaml
  cmr-token/requirements.txt
  cmr-token/src/cmr_token.py
  echo10-construction/cloudformation.yaml
  echo10-construction/requirements.txt
  echo10-construction/src/echo10_construction.py
  echo10-to-cmr/requirements.txt
  environment.yml
  ingest/cloudformation.yaml
  ingest/requirements.txt
  ingest/src/ingest.py
  invoke/cloudformation.yaml
  invoke/requirements.txt
  invoke/src/invoke.py
  notify/cloudformation.yaml
  notify/requirements.txt
  notify/src/notify.py
  requirements-all.txt
  requirements-cmr-token.txt
  requirements-echo10-construction.txt
  requirements-echo10-to-cmr.txt
  requirements-ingest.txt
  requirements-invoke.txt
  requirements-notify.txt
  requirements-verify.txt
  tests/conftest.py
  tests/data/v2/config.json
  tests/data/v2/granule-amplitude.echo10
  tests/data/v2/granule-coherence.echo10
  tests/data/v2/granule-connectedComponents.echo10
  tests/data/v2/granule-unwrappedPhase.echo10
  tests/data/v2/granule.echo10
  tests/data/v2/granule_data.json
  tests/data/v2/inputs.json
  tests/data/v2/sds_metadata.json
  tests/data/v3/config.json
  tests/data/v3/granule-amplitude.echo10
  tests/data/v3/granule-coherence.echo10
  tests/data/v3/granule-connectedComponents.echo10
  tests/data/v3/granule-unwrappedPhase.echo10
  tests/data/v3/granule.echo10
  tests/data/v3/granule_data.json
  tests/data/v3/inputs.json
  tests/data/v3/sds_metadata.json
  tests/test_echo10_construction.py
  tests/test_verify.py
  verify/cloudformation.yaml
  verify/requirements.txt
  verify/src/metadata_schema.json
  verify/src/verify.py
Labels: minor

#211 Document integration testing and remove out-of-date README section
  README.md
  tests/example-message.json
Labels: bumpless
